homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 46.9900
  longitude: 6.9293
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 400
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Zurich
  # Customization file
  customize: !include customize.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

history:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

#weather forecast platfogm
weather:
  - platform: darksky
    api_key: !secret darksky_api
    mode: daily

# Discover some devices automatically
discovery:

#NETGEAR Router
device_tracker:
  - platform: netgear
    password: !secret router_password

#Shopping list configuration
shopping_list:

# Sensors
# PiCamera
camera:
#  - platform: rpi_camera
#    image_width: 640
#    name: living_room_camera
#    image_height: 480
#    image_quality: 50
#    image_rotation:
#    horizontal_flip:
#    vertical_flip: 1
#    timelapse: 1000 #1 picture every 1 second
      
  - platform: mjpeg
    name: Stream Living Room
    username: admin
    password: !secret 5020Lcamera_password
    still_image_url: http://192.168.1.17/image/jpeg.cgi
    mjpeg_url: http://192.168.1.17/video/mjpg.cgi
    authentication: basic

# Weather prediction
sensor:
  - platform: yr
  - platform: darksky
    api_key: !secret darksky_api
    forecast:
      - 0
    hourly_forecast:
      - 0
      - 1
    monitored_conditions:
      - summary
      - icon
      - temperature
      - precip_type
      - precip_intensity
      - apparent_temperature
      - wind_speed
      - cloud_cover
      - humidity
      - hourly_summary
      - sunrise_time
      - sunset_time
      - nearest_storm_distance
 
# AM2302 Temperature and Humidity Sensor
  - platform: dht
    sensor: DHT22
    pin: 23
#    temperature_offset: 2.1
#    humidity_offset: -3.2
    monitored_conditions:
      - temperature
      - humidity

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml

automation: !include automations.yaml
script: !include scripts.yaml